// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Woland-prj/dilemator/internal/services/sessions_service (interfaces: SessionRepositoryPort,HashProviderPort)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package sessions_service_test . SessionRepositoryPort,HashProviderPort
//

// Package sessions_service_test is a generated GoMock package.
package sessions_service_test

import (
	context "context"
	reflect "reflect"
	time "time"

	security_entity "github.com/Woland-prj/dilemator/internal/domain/entity/security_entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepositoryPort is a mock of SessionRepositoryPort interface.
type MockSessionRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryPortMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryPortMockRecorder is the mock recorder for MockSessionRepositoryPort.
type MockSessionRepositoryPortMockRecorder struct {
	mock *MockSessionRepositoryPort
}

// NewMockSessionRepositoryPort creates a new mock instance.
func NewMockSessionRepositoryPort(ctrl *gomock.Controller) *MockSessionRepositoryPort {
	mock := &MockSessionRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepositoryPort) EXPECT() *MockSessionRepositoryPortMockRecorder {
	return m.recorder
}

// FindActiveByUserAgentAndIP mocks base method.
func (m *MockSessionRepositoryPort) FindActiveByUserAgentAndIP(ctx context.Context, userID uuid.UUID, userAgent, ipAddress string) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByUserAgentAndIP", ctx, userID, userAgent, ipAddress)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByUserAgentAndIP indicates an expected call of FindActiveByUserAgentAndIP.
func (mr *MockSessionRepositoryPortMockRecorder) FindActiveByUserAgentAndIP(ctx, userID, userAgent, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByUserAgentAndIP", reflect.TypeOf((*MockSessionRepositoryPort)(nil).FindActiveByUserAgentAndIP), ctx, userID, userAgent, ipAddress)
}

// FindByID mocks base method.
func (m *MockSessionRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionRepositoryPortMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionRepositoryPort)(nil).FindByID), ctx, id)
}

// FindByTokenHash mocks base method.
func (m *MockSessionRepositoryPort) FindByTokenHash(ctx context.Context, tokenHash string) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockSessionRepositoryPortMockRecorder) FindByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockSessionRepositoryPort)(nil).FindByTokenHash), ctx, tokenHash)
}

// Save mocks base method.
func (m *MockSessionRepositoryPort) Save(ctx context.Context, session *security_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepositoryPortMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepositoryPort)(nil).Save), ctx, session)
}

// Update mocks base method.
func (m *MockSessionRepositoryPort) Update(ctx context.Context, session *security_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryPortMockRecorder) Update(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepositoryPort)(nil).Update), ctx, session)
}

// UpdateExpiresAt mocks base method.
func (m *MockSessionRepositoryPort) UpdateExpiresAt(ctx context.Context, id uuid.UUID, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpiresAt", ctx, id, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpiresAt indicates an expected call of UpdateExpiresAt.
func (mr *MockSessionRepositoryPortMockRecorder) UpdateExpiresAt(ctx, id, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpiresAt", reflect.TypeOf((*MockSessionRepositoryPort)(nil).UpdateExpiresAt), ctx, id, expiresAt)
}

// UpdateLastUsedAt mocks base method.
func (m *MockSessionRepositoryPort) UpdateLastUsedAt(ctx context.Context, id uuid.UUID, lastUsedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsedAt", ctx, id, lastUsedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsedAt indicates an expected call of UpdateLastUsedAt.
func (mr *MockSessionRepositoryPortMockRecorder) UpdateLastUsedAt(ctx, id, lastUsedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsedAt", reflect.TypeOf((*MockSessionRepositoryPort)(nil).UpdateLastUsedAt), ctx, id, lastUsedAt)
}

// UpdateRevokeStatus mocks base method.
func (m *MockSessionRepositoryPort) UpdateRevokeStatus(ctx context.Context, id uuid.UUID, revoked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRevokeStatus", ctx, id, revoked)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRevokeStatus indicates an expected call of UpdateRevokeStatus.
func (mr *MockSessionRepositoryPortMockRecorder) UpdateRevokeStatus(ctx, id, revoked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRevokeStatus", reflect.TypeOf((*MockSessionRepositoryPort)(nil).UpdateRevokeStatus), ctx, id, revoked)
}

// MockHashProviderPort is a mock of HashProviderPort interface.
type MockHashProviderPort struct {
	ctrl     *gomock.Controller
	recorder *MockHashProviderPortMockRecorder
	isgomock struct{}
}

// MockHashProviderPortMockRecorder is the mock recorder for MockHashProviderPort.
type MockHashProviderPortMockRecorder struct {
	mock *MockHashProviderPort
}

// NewMockHashProviderPort creates a new mock instance.
func NewMockHashProviderPort(ctrl *gomock.Controller) *MockHashProviderPort {
	mock := &MockHashProviderPort{ctrl: ctrl}
	mock.recorder = &MockHashProviderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashProviderPort) EXPECT() *MockHashProviderPortMockRecorder {
	return m.recorder
}

// GenerateRandomToken mocks base method.
func (m *MockHashProviderPort) GenerateRandomToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRandomToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateRandomToken indicates an expected call of GenerateRandomToken.
func (mr *MockHashProviderPortMockRecorder) GenerateRandomToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRandomToken", reflect.TypeOf((*MockHashProviderPort)(nil).GenerateRandomToken))
}

// Hash mocks base method.
func (m *MockHashProviderPort) Hash(data string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockHashProviderPortMockRecorder) Hash(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockHashProviderPort)(nil).Hash), data)
}

// HashPassword mocks base method.
func (m *MockHashProviderPort) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashProviderPortMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashProviderPort)(nil).HashPassword), password)
}

// VerifyPassword mocks base method.
func (m *MockHashProviderPort) VerifyPassword(hashedPassword, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", hashedPassword, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockHashProviderPortMockRecorder) VerifyPassword(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockHashProviderPort)(nil).VerifyPassword), hashedPassword, password)
}
