// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Woland-prj/dilemator/internal/services/sessions_service (interfaces: SessionService)
//
// Generated by this command:
//
//	mockgen -destination=mock_service.go -package sessions_service . SessionService
//

// Package sessions_service is a generated GoMock package.
package sessions_service

import (
	context "context"
	reflect "reflect"

	security_dto "github.com/Woland-prj/dilemator/internal/domain/dto/security_dto"
	security_entity "github.com/Woland-prj/dilemator/internal/domain/entity/security_entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSessionService) Get(ctx context.Context, id uuid.UUID) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionService)(nil).Get), ctx, id)
}

// Login mocks base method.
func (m *MockSessionService) Login(ctx context.Context, req security_dto.LoginDto, userAgent, ip string) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, userAgent, ip)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockSessionServiceMockRecorder) Login(ctx, req, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockSessionService)(nil).Login), ctx, req, userAgent, ip)
}

// Logout mocks base method.
func (m *MockSessionService) Logout(ctx context.Context, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockSessionServiceMockRecorder) Logout(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockSessionService)(nil).Logout), ctx, sessionToken)
}

// TgLogin mocks base method.
func (m *MockSessionService) TgLogin(ctx context.Context, req *security_dto.TgLoginDto, userAgent, ip string) (*security_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TgLogin", ctx, req, userAgent, ip)
	ret0, _ := ret[0].(*security_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TgLogin indicates an expected call of TgLogin.
func (mr *MockSessionServiceMockRecorder) TgLogin(ctx, req, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TgLogin", reflect.TypeOf((*MockSessionService)(nil).TgLogin), ctx, req, userAgent, ip)
}

// Verify mocks base method.
func (m *MockSessionService) Verify(ctx context.Context, sessionToken string) (*security_entity.UserDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, sessionToken)
	ret0, _ := ret[0].(*security_entity.UserDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockSessionServiceMockRecorder) Verify(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockSessionService)(nil).Verify), ctx, sessionToken)
}
