// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Woland-prj/dilemator/internal/services/dilemma_service (interfaces: DilemmaService)
//
// Generated by this command:
//
//	mockgen -destination=mock_service.go -package dilemma_service . DilemmaService
//

// Package dilemma_service is a generated GoMock package.
package dilemma_service

import (
	context "context"
	reflect "reflect"

	dilemma_dto "github.com/Woland-prj/dilemator/internal/domain/dto/dilemma_dto"
	dilemma_entity "github.com/Woland-prj/dilemator/internal/domain/entity/dilemma_entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDilemmaService is a mock of DilemmaService interface.
type MockDilemmaService struct {
	ctrl     *gomock.Controller
	recorder *MockDilemmaServiceMockRecorder
	isgomock struct{}
}

// MockDilemmaServiceMockRecorder is the mock recorder for MockDilemmaService.
type MockDilemmaServiceMockRecorder struct {
	mock *MockDilemmaService
}

// NewMockDilemmaService creates a new mock instance.
func NewMockDilemmaService(ctrl *gomock.Controller) *MockDilemmaService {
	mock := &MockDilemmaService{ctrl: ctrl}
	mock.recorder = &MockDilemmaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDilemmaService) EXPECT() *MockDilemmaServiceMockRecorder {
	return m.recorder
}

// CreateDilemma mocks base method.
func (m *MockDilemmaService) CreateDilemma(ctx context.Context, req *dilemma_dto.CreateDilemmaDto) (*dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDilemma", ctx, req)
	ret0, _ := ret[0].(*dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDilemma indicates an expected call of CreateDilemma.
func (mr *MockDilemmaServiceMockRecorder) CreateDilemma(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDilemma", reflect.TypeOf((*MockDilemmaService)(nil).CreateDilemma), ctx, req)
}

// CreateDilemmaNode mocks base method.
func (m *MockDilemmaService) CreateDilemmaNode(ctx context.Context, req *dilemma_dto.CreateDilemmaNodeDto) (*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDilemmaNode", ctx, req)
	ret0, _ := ret[0].(*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDilemmaNode indicates an expected call of CreateDilemmaNode.
func (mr *MockDilemmaServiceMockRecorder) CreateDilemmaNode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDilemmaNode", reflect.TypeOf((*MockDilemmaService)(nil).CreateDilemmaNode), ctx, req)
}

// DeleteDilemma mocks base method.
func (m *MockDilemmaService) DeleteDilemma(ctx context.Context, dilemmaID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDilemma", ctx, dilemmaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDilemma indicates an expected call of DeleteDilemma.
func (mr *MockDilemmaServiceMockRecorder) DeleteDilemma(ctx, dilemmaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDilemma", reflect.TypeOf((*MockDilemmaService)(nil).DeleteDilemma), ctx, dilemmaID)
}

// DeleteDilemmaNode mocks base method.
func (m *MockDilemmaService) DeleteDilemmaNode(ctx context.Context, nodeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDilemmaNode", ctx, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDilemmaNode indicates an expected call of DeleteDilemmaNode.
func (mr *MockDilemmaServiceMockRecorder) DeleteDilemmaNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDilemmaNode", reflect.TypeOf((*MockDilemmaService)(nil).DeleteDilemmaNode), ctx, nodeID)
}

// GetByID mocks base method.
func (m *MockDilemmaService) GetByID(ctx context.Context, dilemmaID uuid.UUID) (*dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, dilemmaID)
	ret0, _ := ret[0].(*dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDilemmaServiceMockRecorder) GetByID(ctx, dilemmaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDilemmaService)(nil).GetByID), ctx, dilemmaID)
}

// GetByOwner mocks base method.
func (m *MockDilemmaService) GetByOwner(ctx context.Context, ownerID uuid.UUID, page, size int) ([]dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerID, page, size)
	ret0, _ := ret[0].([]dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockDilemmaServiceMockRecorder) GetByOwner(ctx, ownerID, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockDilemmaService)(nil).GetByOwner), ctx, ownerID, page, size)
}

// GetChildren mocks base method.
func (m *MockDilemmaService) GetChildren(ctx context.Context, parentID uuid.UUID) ([]*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", ctx, parentID)
	ret0, _ := ret[0].([]*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockDilemmaServiceMockRecorder) GetChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockDilemmaService)(nil).GetChildren), ctx, parentID)
}

// GetNodeByID mocks base method.
func (m *MockDilemmaService) GetNodeByID(ctx context.Context, nodeID uuid.UUID) (*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeByID", ctx, nodeID)
	ret0, _ := ret[0].(*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeByID indicates an expected call of GetNodeByID.
func (mr *MockDilemmaServiceMockRecorder) GetNodeByID(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeByID", reflect.TypeOf((*MockDilemmaService)(nil).GetNodeByID), ctx, nodeID)
}

// UpdateDilemma mocks base method.
func (m *MockDilemmaService) UpdateDilemma(ctx context.Context, req *dilemma_dto.UpdateDilemmaDto) (*dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDilemma", ctx, req)
	ret0, _ := ret[0].(*dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDilemma indicates an expected call of UpdateDilemma.
func (mr *MockDilemmaServiceMockRecorder) UpdateDilemma(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDilemma", reflect.TypeOf((*MockDilemmaService)(nil).UpdateDilemma), ctx, req)
}

// UpdateDilemmaNode mocks base method.
func (m *MockDilemmaService) UpdateDilemmaNode(ctx context.Context, req dilemma_dto.UpdateDilemmaNodeDto) (*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDilemmaNode", ctx, req)
	ret0, _ := ret[0].(*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDilemmaNode indicates an expected call of UpdateDilemmaNode.
func (mr *MockDilemmaServiceMockRecorder) UpdateDilemmaNode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDilemmaNode", reflect.TypeOf((*MockDilemmaService)(nil).UpdateDilemmaNode), ctx, req)
}
