// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Woland-prj/dilemator/internal/services/dilemma_service (interfaces: DilemmaRepositoryPort)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package dilemma_service_test . DilemmaRepositoryPort
//

// Package dilemma_service_test is a generated GoMock package.
package dilemma_service_test

import (
	context "context"
	reflect "reflect"

	dilemma_entity "github.com/Woland-prj/dilemator/internal/domain/entity/dilemma_entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDilemmaRepositoryPort is a mock of DilemmaRepositoryPort interface.
type MockDilemmaRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockDilemmaRepositoryPortMockRecorder
	isgomock struct{}
}

// MockDilemmaRepositoryPortMockRecorder is the mock recorder for MockDilemmaRepositoryPort.
type MockDilemmaRepositoryPortMockRecorder struct {
	mock *MockDilemmaRepositoryPort
}

// NewMockDilemmaRepositoryPort creates a new mock instance.
func NewMockDilemmaRepositoryPort(ctrl *gomock.Controller) *MockDilemmaRepositoryPort {
	mock := &MockDilemmaRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockDilemmaRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDilemmaRepositoryPort) EXPECT() *MockDilemmaRepositoryPortMockRecorder {
	return m.recorder
}

// DeleteDilemma mocks base method.
func (m *MockDilemmaRepositoryPort) DeleteDilemma(ctx context.Context, dilemmaID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDilemma", ctx, dilemmaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDilemma indicates an expected call of DeleteDilemma.
func (mr *MockDilemmaRepositoryPortMockRecorder) DeleteDilemma(ctx, dilemmaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDilemma", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).DeleteDilemma), ctx, dilemmaID)
}

// DeleteNode mocks base method.
func (m *MockDilemmaRepositoryPort) DeleteNode(ctx context.Context, nodeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockDilemmaRepositoryPortMockRecorder) DeleteNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).DeleteNode), ctx, nodeID)
}

// GetChildren mocks base method.
func (m *MockDilemmaRepositoryPort) GetChildren(ctx context.Context, parentID uuid.UUID) ([]*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", ctx, parentID)
	ret0, _ := ret[0].([]*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockDilemmaRepositoryPortMockRecorder) GetChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).GetChildren), ctx, parentID)
}

// GetDilemmaWithRoot mocks base method.
func (m *MockDilemmaRepositoryPort) GetDilemmaWithRoot(ctx context.Context, dilemmaID uuid.UUID) (*dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDilemmaWithRoot", ctx, dilemmaID)
	ret0, _ := ret[0].(*dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDilemmaWithRoot indicates an expected call of GetDilemmaWithRoot.
func (mr *MockDilemmaRepositoryPortMockRecorder) GetDilemmaWithRoot(ctx, dilemmaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDilemmaWithRoot", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).GetDilemmaWithRoot), ctx, dilemmaID)
}

// GetDilemmasByOwner mocks base method.
func (m *MockDilemmaRepositoryPort) GetDilemmasByOwner(ctx context.Context, ownerID uuid.UUID, page, size int) ([]dilemma_entity.Dilemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDilemmasByOwner", ctx, ownerID, page, size)
	ret0, _ := ret[0].([]dilemma_entity.Dilemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDilemmasByOwner indicates an expected call of GetDilemmasByOwner.
func (mr *MockDilemmaRepositoryPortMockRecorder) GetDilemmasByOwner(ctx, ownerID, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDilemmasByOwner", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).GetDilemmasByOwner), ctx, ownerID, page, size)
}

// GetNode mocks base method.
func (m *MockDilemmaRepositoryPort) GetNode(ctx context.Context, nodeID uuid.UUID) (*dilemma_entity.DilemmaNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, nodeID)
	ret0, _ := ret[0].(*dilemma_entity.DilemmaNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockDilemmaRepositoryPortMockRecorder) GetNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).GetNode), ctx, nodeID)
}

// LinkParentChild mocks base method.
func (m *MockDilemmaRepositoryPort) LinkParentChild(ctx context.Context, parentID, childID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkParentChild", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkParentChild indicates an expected call of LinkParentChild.
func (mr *MockDilemmaRepositoryPortMockRecorder) LinkParentChild(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkParentChild", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).LinkParentChild), ctx, parentID, childID)
}

// SaveDilemmaDescriber mocks base method.
func (m *MockDilemmaRepositoryPort) SaveDilemmaDescriber(ctx context.Context, dilemma *dilemma_entity.Dilemma) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDilemmaDescriber", ctx, dilemma)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDilemmaDescriber indicates an expected call of SaveDilemmaDescriber.
func (mr *MockDilemmaRepositoryPortMockRecorder) SaveDilemmaDescriber(ctx, dilemma any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDilemmaDescriber", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).SaveDilemmaDescriber), ctx, dilemma)
}

// SaveNode mocks base method.
func (m *MockDilemmaRepositoryPort) SaveNode(ctx context.Context, node *dilemma_entity.DilemmaNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNode", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNode indicates an expected call of SaveNode.
func (mr *MockDilemmaRepositoryPortMockRecorder) SaveNode(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNode", reflect.TypeOf((*MockDilemmaRepositoryPort)(nil).SaveNode), ctx, node)
}
