// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Woland-prj/dilemator/internal/services/users_service (interfaces: UserRepositoryPort,HashProviderPort)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package users_service_test . UserRepositoryPort,HashProviderPort
//

// Package users_service_test is a generated GoMock package.
package users_service_test

import (
	context "context"
	reflect "reflect"

	user_entity "github.com/Woland-prj/dilemator/internal/domain/entity/user_entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryPort is a mock of UserRepositoryPort interface.
type MockUserRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryPortMockRecorder
	isgomock struct{}
}

// MockUserRepositoryPortMockRecorder is the mock recorder for MockUserRepositoryPort.
type MockUserRepositoryPortMockRecorder struct {
	mock *MockUserRepositoryPort
}

// NewMockUserRepositoryPort creates a new mock instance.
func NewMockUserRepositoryPort(ctrl *gomock.Controller) *MockUserRepositoryPort {
	mock := &MockUserRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryPort) EXPECT() *MockUserRepositoryPortMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockUserRepositoryPort) FindByEmail(ctx context.Context, email string) (*user_entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*user_entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryPortMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*user_entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*user_entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryPortMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindByID), ctx, id)
}

// FindByTgID mocks base method.
func (m *MockUserRepositoryPort) FindByTgID(ctx context.Context, id int64) (*user_entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTgID", ctx, id)
	ret0, _ := ret[0].(*user_entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTgID indicates an expected call of FindByTgID.
func (mr *MockUserRepositoryPortMockRecorder) FindByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTgID", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindByTgID), ctx, id)
}

// Save mocks base method.
func (m *MockUserRepositoryPort) Save(ctx context.Context, user *user_entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryPortMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepositoryPort)(nil).Save), ctx, user)
}

// MockHashProviderPort is a mock of HashProviderPort interface.
type MockHashProviderPort struct {
	ctrl     *gomock.Controller
	recorder *MockHashProviderPortMockRecorder
	isgomock struct{}
}

// MockHashProviderPortMockRecorder is the mock recorder for MockHashProviderPort.
type MockHashProviderPortMockRecorder struct {
	mock *MockHashProviderPort
}

// NewMockHashProviderPort creates a new mock instance.
func NewMockHashProviderPort(ctrl *gomock.Controller) *MockHashProviderPort {
	mock := &MockHashProviderPort{ctrl: ctrl}
	mock.recorder = &MockHashProviderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashProviderPort) EXPECT() *MockHashProviderPortMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockHashProviderPort) HashPassword(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashProviderPortMockRecorder) HashPassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashProviderPort)(nil).HashPassword), arg0)
}

// VerifyPassword mocks base method.
func (m *MockHashProviderPort) VerifyPassword(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockHashProviderPortMockRecorder) VerifyPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockHashProviderPort)(nil).VerifyPassword), arg0, arg1)
}
